stack = []
stack.append(1)  
stack.append(2)
stack.append(10)
stack.pop() 
stack.append(3)
stack.append(10)
stack.append(2)
stack.pop() 
stack.append(10)
stack.pop()      
print(stack)
print(stack[-1])     